# Generated by Django 3.1.7 on 2021-02-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_fill_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=8, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_exchange',
            field=models.DecimalField(decimal_places=8, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
    ]
