# Generated by Django 3.1.7 on 2021-02-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210223_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='currency_product',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantity',
        ),
    ]
