# Generated by Django 3.1.7 on 2021-02-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210223_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='currency_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
